### PR TITLE
Make opproto public in fluent library.

### PR DESCRIPTION
**Pull request by robshakir**
```
  * (M) fluent/fluent.go
  * (M) fluent/fluent_test.go
    - To allow clients that are building examples using the fluent
      library to create AFTOperation protobufs, expose opproto - which
      returns an AFTOperation protobuf - publicly.
```

### CODE REVIEW

**Review by sthesayi — APPROVED** [review]

**Review by liulk — COMMENTED** [review]
How is this going to be used? GRIBIEntry was already made exported, which allows callers to stage the entries in a helper function before calling fluent client.Modify().AddEntry().

**Comment by robshakir** [comment]
It is used for constructing operations outside of the context of testing with this API. 

We are creating some example message structures to be shared which need us to be able to share a set of `AFTOperation` messages. This allows us to use the fluent API to construct those.

**Review by liulk — APPROVED** [review]

**Comment by robshakir** [comment]
Actually, thinking about this further - one option would be to make `entriesToModifyRequest` public (https://github.com/openconfig/gribigo/blob/11c313ab4dd9b05d32c1dc337f37b7c76d71802c/fluent/fluent.go#L388), this would allow `GRIBIEntry` instances to be constructed and then call this. Essentially, in `fluent` we created a wrapper for `AFTEntry` and `AFTOperation` within gRIBI.

**Comment by liulk** [comment]
The function `entriesToModifyRequest` seems to be doing a lot more than just converting the entries: set the operation type, counting the operation ID, and populating the election ID from the connection. I'm not sure whether these side-effects may have unintended consequences to the connection state.

Since the GRIBIEntry interface already has exported EntryProto(), I think exporting OpProto() should be fine. It looks like both are actually very similar.

(I think OpProto() is for writing to the device, and EntryProto() reconstructs what should be read from the device?)

**Comment by robshakir** [comment]
Yes, that's correct. SGTM, I'll go ahead with this PR.

**Pull request merged**
